### ISSUE TITLE
Compilation failure on previous version (2017.3)

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2152]
Introduced by #2149

```
AppEngineGradlePluginFacetType.java:77: error: AppEngineGradlePluginFacetConfiguration is not abstract and does not override abstract method writeExternal(Element) in FacetConfiguration
  public static class AppEngineGradlePluginFacetConfiguration
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```
