### PR TITLE
Implement interface methods for 2017.3

### LINKED ISSUE #2152: Compilation failure on previous version (2017.3)
Introduced by #2149

```
AppEngineGradlePluginFacetType.java:77: error: AppEngineGradlePluginFacetConfiguration is not abstract and does not override abstract method writeExternal(Element) in FacetConfiguration
  public static class AppEngineGradlePluginFacetConfiguration
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #2152 

In 2017.3 readExternal and writeExternal are deprecated regular interface methods (so they need to be implemented). 

In 2018.1 they are made default methods so no impl in needed. This adds an empty impl to quiet 2017.3.

### CODE REVIEW

**Comment by etanshaul** [comment]
why they decided to make the default instead of removing them is beyond me..
