### ISSUE TITLE
EAP build broken again

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2287]
```
:stackdriver-debugger:compileTestJava/tmpfs/src/github/google-cloud-intellij/stackdriver-debugger/testSrc/com/google/cloud/tools/intellij/stackdriver/debugger/CloudDebugProcessStateTest.java:66: error: cannot find symbol
    IdeaTestCase.initPlatformPrefix();
                ^
  symbol:   method initPlatformPrefix()
  location: class IdeaTestCase
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

**Comment by fgloppe** [comment]
Hi, do you have any plans to make the plugin available for the 2018.3 version that has been released ? Thanks.

**Comment by etanshaul** [comment]
Yes. We will get this working ASAP. Thanks.

**Comment by etanshaul** [comment]
@fgloppe - Just to update you on this. We have a release ready to go that will fix the plugin for 2018.3. Stay tuned for a new release that will come out in the next couple of days after we verify it.

If you wanted to get your hands on it sooner, then you can install the staged version of the release that lives in the alpha repo. To install an alpha version of the plugin, follow the pre-release instructions here https://github.com/GoogleCloudPlatform/google-cloud-intellij#pre-releases. The version you should see after configuring the alpha repo is **18.11.1**, which should work with 2018.3.

**Comment by fgloppe** [comment]
Thanks a lot ! It works for me although I had this error when I launched Intellij with this version of the plugin for the first time:
`com.intellij.diagnostic.PluginException: com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.AppEngineStandardLocalRunToolsMenuAction (GoogleCloudTools.AppEngineStandardLocalRun): group with id "GoogleCloudTools.AppEngine" isn't registered; action will be added to the "Other" group [Plugin: com.google.gct.core]`

Thanks again !

**Comment by Splaktar** [comment]
Can we update the title of this? The stable build is broken now, not just the EAP. People looking for related issues who aren't on the EAP will ignore this issue.

Hope to see a fix soon. I will be happy to verify it.

**Comment by etanshaul** [comment]
Title updated, thanks. A fix is in the works. Will update here when released. Sorry for the inconvenience.

**Comment by etanshaul** [comment]
@Splaktar @fgloppe 

Cloud Tools for IntelliJ plugin version 18.11.1 was just released. This should fix the problem with the plugin running in the latest version of IntelliJ (2018.3). Thanks for reporting the issue and for your patience.

Please let us know if things still don't work as expected.

**Comment by etanshaul** [comment]
oh and just in case - if you previously tried the alpha, you may want to remove the alpha repository URL from the the plugin manager settings in IntelliJ, just to be sure that you are pulling the stable version going forward.
